name: Deploy Prod

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3

      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: use Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.0
          profile: minimal
          override: true

      - name: add aarch64-unknown-linux-gnu
        run: rustup target add aarch64-unknown-linux-gnu

      - name: use Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.10.0

      - name: use Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: cargo-lambda/cargo-lambda
          platform: linux
          arch: x86_64 # | aarch64

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: add openssl
        run: cargo add openssl@0.10.45 --features vendored

      - name: pnpm deploy
        run: |
          set -euxo pipefail
          pnpm sst deploy --stage prod

    env:
      STAGE: prod
      LOG_LEVEL: info
      MONGO_URI: ${{ secrets.MONGO_URI }}
      ELEVEN_LABS_API_KEY: ${{ secrets.ELEVEN_LABS_API_KEY }}
      AUTHENTICATION_TOKEN: ${{ secrets.AUTHENTICATION_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
